# Generated by Django 3.0.8 on 2022-11-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('credito', models.IntegerField()),
                ('professor', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'curso-db',
            },
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='curso',
            new_name='cpf',
        ),
        migrations.AddField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
