# Generated by Django 3.0.8 on 2022-11-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('curso', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
            ],
            options={
                'db_table': 'aluno-db',
            },
        ),
    ]
